spring.application.name=uq-ai-backend
server.port=8080

# Configuración de la Base de Datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:BD_ortiz_junior_T1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola H2 para validar datos visualmente en desarrollo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Clave secreta robusta para firmar los JWT (Fundamental para Programación Segura)
jwt.secret=uqAiSolutionSecretKey2026ProgramacionSeguraDD281OrtizJunior
jwt.expiration=86400000

# Permitir conexión con el servidor local del Frontend (Next.js)
cors.allowed.origins=http://localhost:3000